### ISSUE TITLE
Correction in the documentation

### ISSUE THREAD

**Issue by Rohit-Satyam** [sofpn/rprimer#4]
Kindly correct this in document
Instead of 
```
myOligos <- oligos(myConsensusProfile)
myAssays <- assays(myOligos)

```
it should be

```
myOligos <- designOligos(myConsensusProfile)
myAssays <- designAssays(myOligos)
```
https://github.com/sofpn/rprimer/blob/4a2dc809a427fe0ded30d8dcb5d968ea68b3b7d6/vignettes/getting-started-with-rprimer.Rmd#L472

**Comment by Rohit-Satyam** [comment]
Running the following command in tutorial give me an errror

```r
write.csv(myAssays, file = "myAssays.csv", quote = FALSE, row.names = FALSE)

Error in utils::write.table(myAssays, file = "myAssays_mafft.csv", quote = FALSE,  : 
  unimplemented type 'list' in 'EncodeElement'
```

**Comment by sofpn** [comment]
Hi. Sorry for my very late reply, thanks for noticing! I have now corrected it in the vignette. However, I could not reproduce the error from your second comment, I do not get an error message when I run this code (the last line is copy-pasted from the vingette.

`data("exampleRprimerAssay")
myAssays <- exampleRprimerAssay
write.csv(myAssays, file = "myAssays.csv", quote = FALSE, row.names = FALSE)
`
I will look at the other Issue you posted as soon as possible. 

Best regards,
Sofia
