### ISSUE TITLE
Possible nucleotide assignment error in reverse primer ouput - S and W the wrong way around in reverse primers

### ISSUE THREAD

**Issue by lucienalperstein** [sofpn/rprimer#5]
Hi there, 

I'm using RPrimer to design some degenerate primers.

In the designAssays step when my outputs are listed with an S or W in the reverse primer I get no matches when I double-check the primer against the sequence I used to design the primers (using the reverse complement). However, if I swap to S and W I get significantly more hits, in line with the coverageFwd results.
This does not occur in the forward primer sequence. 

Can you please let me know if there will be a fix for this issue, or if not where I can update this in the script files?

Kindly,
Lucien

**Comment by sofpn** [comment]
Thank you for noticing! I believe it comes from an error in a lookup table (see my last commit). I'll push the fix to the Bioconductor repository as soon as possible. At the moment I'm having some problems with my login and credentials, so it may take a few days. Let me know if the error still occurs, and sorry for the inconvenience.

Cheers, 
Sofia
